//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        public long CartItemID { get; set; }
        public long ItemID { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public long AppUserID { get; set; }
        public long OrderID { get; set; }
        public System.DateTime DateAdded { get; set; }
        public bool IsOrdered { get; set; }
        public System.DateTime DateOrdered { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Item Item { get; set; }
        public virtual Order Order { get; set; }
    }
}
