//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPA
    {
        public long CPAID { get; set; }
        public long CPAStageID { get; set; }
        public System.DateTime StartDate { get; set; }
        public long CartID { get; set; }
    
        public virtual CPAStage CPAStage { get; set; }
    }
}
