//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.CartItem = new HashSet<CartItem>();
        }
    
        public long OrderID { get; set; }
        public string Description { get; set; }
        public decimal Budget { get; set; }
        public System.DateTime DateCreated { get; set; }
        public long AppUserID { get; set; }
        public string Comment { get; set; }
        public System.DateTime DeliveryDate { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual ICollection<CartItem> CartItem { get; set; }
    }
}
